jobs:
  core:
    env:
      JDK_VERSION: ${{ matrix.jdk }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-sonar
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.jdk == 17 && github.event_name
        == 'push' }}
      name: Test WireMock with Sonarqube
      run: ./gradlew :check :sonarqube --stacktrace --no-daemon
    - continue-on-error: true
      name: Test WireMock
      run: ./gradlew :check --stacktrace --no-daemon
    - continue-on-error: true
      if: always()
      name: Archive WireMock test report - ${{ matrix.os }} JDK ${{ matrix.jdk }}
      uses: actions/upload-artifact@v2
      with:
        name: wiremock-core-test-report-${{ matrix.os }} JDK ${{ matrix.jdk }}
        path: 'build/reports/tests/test

          build/test-results/test

          '
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 11
        - 17
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
  jetty12:
    env:
      JDK_VERSION: ${{ matrix.jdk }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-jetty12-sonar
        path: ~/.sonar/cache
        restore-keys: ${{ runner.os }}-jetty12-sonar
    - continue-on-error: true
      if: ${{ !(matrix.os == 'ubuntu-latest' && github.event_name == 'push') }}
      name: Test Jetty12 JAR
      run: ./gradlew :wiremock-jetty12:check --stacktrace --no-daemon
    - continue-on-error: true
      if: always()
      name: Archive Jetty12 test report - ${{ matrix.os }} JDK ${{ matrix.jdk }}
      uses: actions/upload-artifact@v2
      with:
        name: wiremock-jetty12-test-report-${{ matrix.os }} JDK ${{ matrix.jdk }}
        path: 'wiremock-jetty12/build/reports/tests/test

          wiremock-jetty12/build/test-results/test

          '
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - 17
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: Build and test
on:
  repository_dispatch:
    types: trigger-ga___build-and-test.yml
