jobs:
  update_release_draft:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: release-drafter/release-drafter@v5
      with:
        name: next
        tag: next
        version: next
name: Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___changelog-draft.yml
