jobs:
  publish-core:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      id: publish_package
      name: Publish core package
      run: ./gradlew :publish :closeAndReleaseStagingRepositories --stacktrace
  publish-jetty12:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      id: publish_package
      name: Publish Jetty 12 package
      run: ./gradlew :wiremock-jetty12:publish :closeAndReleaseStagingRepositories
        --stacktrace
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
